language: java
sudo: required


jdk:
  - openjdk8


services:
  - docker
env:
  global:
    - BUILD_ID=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_a9281aa73682_key -iv $encrypted_a9281aa73682_iv -in t-computer-271414-098072aeb5e5.json.enc -out app/t-computer-271414-098072aeb5e5.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project t-computer-271414
  - gcloud config set compute/zone us-central1-c
  - gcloud container clusters get-credentials cluster-1
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  
script:
  - mvn -f contacts-backend/pom.xml clean verify -P prod
  
  
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master